name: Deploy KTT app on EC2

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and install required dependencies + clone project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo yum update -y
            sudo yum install -y docker git
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
            sudo chmod 666 /var/run/docker.sock
            
            sudo dnf install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx

            # Clone or update the project repo
            git config --global --add safe.directory /home/${{ secrets.EC2_USER }}/BBT
            if [ -d "BBT" ]; then
              cd BBT
              git config pull.rebase false
              git checkout BBT
              git fetch origin BBT
              git reset --hard origin/BBT
            else
              git clone -b develop https://${{ secrets.PAT_GITHUB }}@github.com/bellblaze/BBT.git
            fi
      
  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: SSH into EC2 and configure NGINX
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Step 1: Remove old containers and images
            docker container rm document-chatbot-container dataforecast-chatbot-container -f
            docker system prune -a -f
            
            # Step 2: Navigate to chatbot directory
            cd /home/ec2-user/BBT/BBT-Admin-Backend/AI/chatbots/

            # Step 3: Build Docker images
            echo "Building document-chatbot image..."
            cd document-chatbot
            docker build -t document-chatbot .
            echo "Building dataforecast-chatbot image..."
            cd ../dataforecast-chatbot
            docker build -t dataforecast-chatbot .



  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into EC2 and deploy container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Step 1: Navigate to chatbot directory
            cd /home/ec2-user/BBT/BBT-Admin-Backend/AI/chatbots/

            # Step 2: Run Docker Containers
            echo "Deploying document-chatbot image..."
            cd document-chatbot
            docker run --restart always -d -p 8501:8501 --name document-chatbot-container document-chatbot

            echo "Deploying dataforecast-chatbot image..."
            cd ../dataforecast-chatbot
            docker run --restart always -d -p 8502:8501 --name dataforecast-chatbot-container dataforecast-chatbot

            # Step 3: Configure Nginx
            echo "Configuring Nginx..."  
            if [ ! -f /etc/nginx/conf.d/bellblaze-poc.conf ]; then
              sudo tee /etc/nginx/conf.d/bellblaze-poc.conf > /dev/null << 'EOF'
              server {
                  listen 80;
                  server_name aiplay.bellblazetech.com;
              
                  location / {
                      return 301 https://$host$request_uri;
                  }
              }
              
              server {
                  listen 443 ssl;
                  server_name aiplay.bellblazetech.com;
              
                  ssl_certificate /etc/letsencrypt/live/aiplay.bellblazetech.com/fullchain.pem;
                  ssl_certificate_key /etc/letsencrypt/live/aiplay.bellblazetech.com/privkey.pem;
                  ssl_protocols TLSv1.2 TLSv1.3;
                  ssl_ciphers HIGH:!aNULL:!MD5;
              
                  location /pricing-calculator/ {
                      proxy_pass http://localhost:5500/;
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header X-Forwarded-Proto $scheme;
                      proxy_http_version 1.1;
                      proxy_set_header Upgrade $http_upgrade;
                      proxy_set_header Connection 'upgrade';
                      proxy_read_timeout 86400;
                  }
              
                  location /dataforecast-chatbot/ {
                      proxy_pass http://localhost:8502/dataforecast-chatbot/;  
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header X-Forwarded-Proto $scheme;
                      proxy_http_version 1.1;
                      proxy_set_header Upgrade $http_upgrade;
                      proxy_set_header Connection 'upgrade';
                      proxy_read_timeout 86400;
                  }
                  
                  location /document-chatbot/ {
                      proxy_pass http://localhost:8501/;
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header X-Forwarded-Proto $scheme;
                      proxy_http_version 1.1;
                      proxy_set_header Upgrade $http_upgrade;
                      proxy_set_header Connection 'upgrade';
                      proxy_read_timeout 86400;
                  }
              }
              EOF
                            sudo nginx -t && sudo systemctl reload nginx
                          else
                            echo "Config file already exists. Skipping creation."
                          fi
